## Import Libraries

We import the required libraries for data analysis and visualization.

- **pandas** → used for handling datasets and tables  
- **numpy** → used for numerical operations  
- **matplotlib** → used for basic plotting  
- **seaborn** → used for better statistical visualizations

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Load Dataset

Load the loan dataset using **pandas**, then preview the first rows to understand the structure.

- `pd.read_csv()` → loads the CSV file  
- `df.head()` → shows the first 5 rows

### 📐 df.shape

Shows the **dimensions of the dataset**.

```python
df.shape

In [2]:
df=pd.read_csv("loan_prediction.csv")
df.shape

(614, 13)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    str
 1   Gender             601 non-null    str
 2   Married            611 non-null    str
 3   Dependents         599 non-null    str
 4   Education          614 non-null    str
 5   Self_Employed      582 non-null    str
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    str
 12  Loan_Status        614 non-null    str
dtypes: float64(4), int64(1), str(8)
memory usage: 62.5 KB

In [4]:
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [5]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [6]:
df["Gender"].value_counts()

Gender
Male      489
Female    112
Name: count, dtype: int64

In [7]:
df["Gender"]=df["Gender"].fillna(df["Gender"].mode()[0])

In [8]:
df["Married"].value_counts()

Married
Yes    398
No     213
Name: count, dtype: int64

In [9]:
df["Married"]=df["Married"].fillna(df["Married"].mode()[0])

In [10]:
df["Dependents"].value_counts()

Dependents
0     345
1     102
2     101
3+     51
Name: count, dtype: int64

In [11]:
df["Dependents"].unique()

<StringArray>
['0', '1', '2', '3+', nan]
Length: 5, dtype: str

In [12]:
df["Dependents"].head(10)

0     0
1     1
2     0
3     0
4     0
5     2
6     0
7    3+
8     2
9     1
Name: Dependents, dtype: str

In [13]:
df["Dependents"]=df["Dependents"].replace("3+","3")

In [15]:
df["Dependents"]=df["Dependents"].fillna(df["Dependents"].mode()[0])

In [16]:
df["Dependents"]=df["Dependents"].astype(int)

In [17]:
df["Dependents"].unique()

array([0, 1, 2, 3])

In [18]:
df["Self_Employed"].value_counts()

Self_Employed
No     500
Yes     82
Name: count, dtype: int64

In [19]:
df["Self_Employed"].isnull().sum()

np.int64(32)

In [20]:
df["Self_Employed"]=df["Self_Employed"].fillna(df["Self_Employed"].mode()[0])

In [22]:
df["LoanAmount"].value_counts()

LoanAmount
120.0    20
110.0    17
100.0    15
187.0    12
160.0    12
         ..
292.0     1
142.0     1
350.0     1
496.0     1
253.0     1
Name: count, Length: 203, dtype: int64

In [23]:
df["LoanAmount"]=df["LoanAmount"].fillna(df["LoanAmount"].median())

In [24]:
df["Loan_Amount_Term"].value_counts()

Loan_Amount_Term
360.0    512
180.0     44
480.0     15
300.0     13
240.0      4
84.0       4
120.0      3
60.0       2
36.0       2
12.0       1
Name: count, dtype: int64

In [25]:
df["Loan_Amount_Term"]=df["Loan_Amount_Term"].fillna(df["Loan_Amount_Term"].median())

In [26]:
df["Credit_History"]=df["Credit_History"].fillna(df["Credit_History"].mode()[0])

In [27]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

# Encoding

In [28]:
from sklearn.preprocessing import LabelEncoder

In [29]:
le=LabelEncoder()

In [30]:
bin_colmns=["Gender","Married","Education","Self_Employed","Loan_Status"]

In [32]:
for col in bin_colmns:
    df[col]=le.fit_transform(df[col])

In [34]:
df=pd.get_dummies(df,columns=["Property_Area"])

In [35]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
0,LP001002,1,0,0,0,0,5849,0.0,128.0,360.0,1.0,1,False,False,True
1,LP001003,1,1,1,0,0,4583,1508.0,128.0,360.0,1.0,0,True,False,False
2,LP001005,1,1,0,0,1,3000,0.0,66.0,360.0,1.0,1,False,False,True
3,LP001006,1,1,0,1,0,2583,2358.0,120.0,360.0,1.0,1,False,False,True
4,LP001008,1,0,0,0,0,6000,0.0,141.0,360.0,1.0,1,False,False,True

In [36]:
cols=[col for col in df.columns if "Property_Area" in col]
df[cols]=df[cols].astype(int)

In [37]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
0,LP001002,1,0,0,0,0,5849,0.0,128.0,360.0,1.0,1,0,0,1
1,LP001003,1,1,1,0,0,4583,1508.0,128.0,360.0,1.0,0,1,0,0
2,LP001005,1,1,0,0,1,3000,0.0,66.0,360.0,1.0,1,0,0,1
3,LP001006,1,1,0,1,0,2583,2358.0,120.0,360.0,1.0,1,0,0,1
4,LP001008,1,0,0,0,0,6000,0.0,141.0,360.0,1.0,1,0,0,1